/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407xx.h"
#include "stm32f407xx_gpio_driver.h"
#include "stm32f407xx_spi_driver.h"
#include <string.h>

/*
SPI2 LOOPBACK CONNECTION:
PB15 (MOSI) ---- PB14 (MISO)
*/

SPI_Handle_t SPI2handle;

char user_data[] = "Hello world";
char read_buffer[32];

volatile uint8_t rxComplete = 0;

/* ================= DELAY ================= */
void delay(void)
{
    for(uint32_t i = 0; i < 500000; i++);
}

/* ================= GPIO INIT ================= */
void SPI2_GPIOInits(void)
{
    GPIO_Handle_t SPIPins;

    GPIO_PeriClockControl(GPIOB, ENABLE);

    SPIPins.pGPIOx = GPIOB;
    SPIPins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
    SPIPins.GPIO_PinConfig.GPIO_PinAltFunMode = 5;
    SPIPins.GPIO_PinConfig.GPIO_PinOPtype = GPIO_OP_TYPE_PP;
    SPIPins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    SPIPins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

    // SCLK
    SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
    GPIO_Init(&SPIPins);

    // MISO
    SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
    GPIO_Init(&SPIPins);

    // MOSI
    SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
    GPIO_Init(&SPIPins);
}

/* ================= SPI INIT ================= */
void SPI2_Init(void)
{
    SPI_PeriClockControl(SPI2, ENABLE);

    SPI2handle.pSPIx = SPI2;
    SPI2handle.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;
    SPI2handle.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
    SPI2handle.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV128;
    SPI2handle.SPIConfig.SPI_DFF = SPI_DFF_8BITS;
    SPI2handle.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
    SPI2handle.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
    SPI2handle.SPIConfig.SPI_SSM = SPI_SSM_EN;

    SPI_Init(&SPI2handle);
}

/* ================= LED INIT ================= */
void GPIO_LEDInit(void)
{
    GPIO_Handle_t GpioLed;

    GPIO_PeriClockControl(GPIOD, ENABLE);

    GpioLed.pGPIOx = GPIOD;
    GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
    GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

    GPIO_Init(&GpioLed);
}

/* ================= MAIN ================= */
int main(void)
{
    GPIO_LEDInit();
    SPI2_GPIOInits();
    SPI2_Init();

    SPI_IRQInterruptConfig(IRQ_NO_SPI2, ENABLE);

    SPI_SSIConfig(SPI2, ENABLE);
    SPI_PeripheralControl(SPI2, ENABLE);

    while(1)
    {

        // Start receive FIRST
        SPI_ReceiveDataIT(&SPI2handle,
                          (uint8_t*)read_buffer,
                          strlen(user_data));

        uint8_t dummy = user_data[0];  // first byte

        SPI2->DR = dummy;
        // Start transmit
        SPI_SendDataIT(&SPI2handle,(uint8_t*)user_data,
            	                       strlen(user_data));


        // Wait until reception complete
        while(!rxComplete);

        rxComplete = 0;

        delay();
    }
}

/* ================= ISR ================= */
void SPI2_IRQHandler(void)
{
    SPI_IRQHandling(&SPI2handle);
}

/* ================= CALLBACK ================= */
void SPI_ApplicationEventCallback(SPI_Handle_t *pSPIHandle, uint8_t AppEv)
{
    if(AppEv == SPI_EVENT_RX_CMPLT)
    {
        // Null terminate string
        read_buffer[strlen(user_data)] = '\0';

        // Toggle LED (PROOF OF SUCCESS)
        GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);

        rxComplete = 1;
    }
}
